runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /mudd/essay
  static_files: static/mudd/index.html
  upload: static/mudd/index.html
- url: /mudd/create
  static_files: static/mudd/create.html
  upload: static/mudd/create.html
- url: /static
  static_dir: static
- url: /.*
  script: main.app


