# TODO: delete and put on my server
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /skiline/
  static_files: skiline/index.html
  upload: skiline/index.html

- url: /(.*)
  static_files: \1
  upload: (.*)

